### ISSUE TITLE
Error in Binder

### ISSUE THREAD

**Issue by elyarzv** [RoboStack/jupyterlab-ros#23]
There is a problem in launching the binder. I am not sure the problem is related to mybinder.org or jupyterlab-ros repo.
The error says: 
**Cannot open**
Invalid response: 503 Service Unavailable

**Comment by hbcarlos** [comment]
Hi @elyarzv, thanks for opening this issue.

We pushed some commits to master to make the binder demo work.

Give it a try, and feel free to reopen if there is something wrong.

I deactivated jupyter-ros since seams are not compatible with JupyterLab 3. The interactive widgets in the notebook won't work.
I'll add it again once jupyter-ros is updated.

**Comment by ktaletsk** [comment]
Binder seem to have a similar error again. I am attaching the screen recording in hopes to help identify the issue

https://user-images.githubusercontent.com/8834829/149572462-76a7fc01-0bfc-4edd-8beb-33e6b97721a4.mov
